language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm
matrix:
  include:
    - php: 5.6
      env: COVERALLS=true
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer selfupdate
  - travis_retry composer i --no-interaction --prefer-source

script:
  - ./vendor/bin/psalm
  - ./vendor/phpunit/phpunit/phpunit -c phpunit.xml

after_success:
  - test -z $COVERALLS || (composer require satooshi/php-coveralls && vendor/bin/coveralls -v)
